# ============================================================
# DDR2LP
# ============================================================

set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CA[0]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CA[1]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CA[2]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CA[3]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CA[4]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CA[5]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CA[6]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CA[7]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CA[8]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CA[9]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CKE[0]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CKE[1]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V HSUL" -to DDR2LP_CK_n
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V HSUL" -to DDR2LP_CK_p
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CS_n[0]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_CS_n[1]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DM[0]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DM[1]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DM[2]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DM[3]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[0]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[1]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[2]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[3]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[4]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[5]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[6]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[7]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[8]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[9]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[10]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[11]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[12]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[13]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[14]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[15]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[16]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[17]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[18]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[19]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[20]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[21]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[22]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[23]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[24]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[25]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[26]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[27]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[28]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[29]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[30]
set_instance_assignment -name IO_STANDARD "1.2-V HSUL" -to DDR2LP_DQ[31]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V HSUL" -to DDR2LP_DQS_n[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V HSUL" -to DDR2LP_DQS_n[1]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V HSUL" -to DDR2LP_DQS_n[2]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V HSUL" -to DDR2LP_DQS_n[3]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V HSUL" -to DDR2LP_DQS_p[0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V HSUL" -to DDR2LP_DQS_p[1]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V HSUL" -to DDR2LP_DQS_p[2]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V HSUL" -to DDR2LP_DQS_p[3]
set_instance_assignment -name IO_STANDARD "1.2 V" -to DDR2LP_OCT_RZQ

set_location_assignment PIN_AE6 -to DDR2LP_CA[0]
set_location_assignment PIN_AF6 -to DDR2LP_CA[1]
set_location_assignment PIN_AF7 -to DDR2LP_CA[2]
set_location_assignment PIN_AF8 -to DDR2LP_CA[3]
set_location_assignment PIN_U10 -to DDR2LP_CA[4]
set_location_assignment PIN_U11 -to DDR2LP_CA[5]
set_location_assignment PIN_AE9 -to DDR2LP_CA[6]
set_location_assignment PIN_AF9 -to DDR2LP_CA[7]
set_location_assignment PIN_AB12 -to DDR2LP_CA[8]
set_location_assignment PIN_AB11 -to DDR2LP_CA[9]
set_location_assignment PIN_AF14 -to DDR2LP_CKE[0]
set_location_assignment PIN_AE13 -to DDR2LP_CKE[1]
set_location_assignment PIN_P10 -to DDR2LP_CK_n
set_location_assignment PIN_N10 -to DDR2LP_CK_p
set_location_assignment PIN_R11 -to DDR2LP_CS_n[0]
set_location_assignment PIN_T11 -to DDR2LP_CS_n[1]
set_location_assignment PIN_AF11 -to DDR2LP_DM[0]
set_location_assignment PIN_AE18 -to DDR2LP_DM[1]
set_location_assignment PIN_AE20 -to DDR2LP_DM[2]
set_location_assignment PIN_AE24 -to DDR2LP_DM[3]
set_location_assignment PIN_AA14 -to DDR2LP_DQ[0]
set_location_assignment PIN_Y14 -to DDR2LP_DQ[1]
set_location_assignment PIN_AD11 -to DDR2LP_DQ[2]
set_location_assignment PIN_AD12 -to DDR2LP_DQ[3]
set_location_assignment PIN_Y13 -to DDR2LP_DQ[4]
set_location_assignment PIN_W12 -to DDR2LP_DQ[5]
set_location_assignment PIN_AD10 -to DDR2LP_DQ[6]
set_location_assignment PIN_AF12 -to DDR2LP_DQ[7]
set_location_assignment PIN_AC15 -to DDR2LP_DQ[8]
set_location_assignment PIN_AB15 -to DDR2LP_DQ[9]
set_location_assignment PIN_AC14 -to DDR2LP_DQ[10]
set_location_assignment PIN_AF13 -to DDR2LP_DQ[11]
set_location_assignment PIN_AB16 -to DDR2LP_DQ[12]
set_location_assignment PIN_AA16 -to DDR2LP_DQ[13]
set_location_assignment PIN_AE14 -to DDR2LP_DQ[14]
set_location_assignment PIN_AF18 -to DDR2LP_DQ[15]
set_location_assignment PIN_AD16 -to DDR2LP_DQ[16]
set_location_assignment PIN_AD17 -to DDR2LP_DQ[17]
set_location_assignment PIN_AC18 -to DDR2LP_DQ[18]
set_location_assignment PIN_AF19 -to DDR2LP_DQ[19]
set_location_assignment PIN_AC17 -to DDR2LP_DQ[20]
set_location_assignment PIN_AB17 -to DDR2LP_DQ[21]
set_location_assignment PIN_AF21 -to DDR2LP_DQ[22]
set_location_assignment PIN_AE21 -to DDR2LP_DQ[23]
set_location_assignment PIN_AE15 -to DDR2LP_DQ[24]
set_location_assignment PIN_AE16 -to DDR2LP_DQ[25]
set_location_assignment PIN_AC20 -to DDR2LP_DQ[26]
set_location_assignment PIN_AD21 -to DDR2LP_DQ[27]
set_location_assignment PIN_AF16 -to DDR2LP_DQ[28]
set_location_assignment PIN_AF17 -to DDR2LP_DQ[29]
set_location_assignment PIN_AD23 -to DDR2LP_DQ[30]
set_location_assignment PIN_AF23 -to DDR2LP_DQ[31]
set_location_assignment PIN_W13 -to DDR2LP_DQS_n[0]
set_location_assignment PIN_V14 -to DDR2LP_DQS_n[1]
set_location_assignment PIN_W15 -to DDR2LP_DQS_n[2]
set_location_assignment PIN_W17 -to DDR2LP_DQS_n[3]
set_location_assignment PIN_V13 -to DDR2LP_DQS_p[0]
set_location_assignment PIN_U14 -to DDR2LP_DQS_p[1]
set_location_assignment PIN_V15 -to DDR2LP_DQS_p[2]
set_location_assignment PIN_W16 -to DDR2LP_DQS_p[3]
set_location_assignment PIN_AE11 -to DDR2LP_OCT_RZQ
