# MIPSfpga-plus makefile
# Stanislav Zhelnio, 2017-2019

# this .mk file current dir
CUR_DIR := $(realpath $(dir $(lastword $(MAKEFILE_LIST))))

CSOURCES += main.c

include $(CUR_DIR)/../../global.mk
include $(COMMON_PROGRAM)/build.mk
